baseurl = "http://getwt.io/"
languageCode = "en-us"
title = "Wellington - Open Source CSS Preprocesser with Spriting!"
theme = "herring-cove"

[params]
ProfilePicture = "/images/profile.png"
enableLandingPage = true
AuthorName = "Drew Wells"

[params.links]
Docs = "/docs/"
Examples = "/examples/"
