baseurl = "http://getwt.io/"
languageCode = "en-us"
title = "Wellington"
theme = "herring-cove"

[params]
Description = "Open Source CSS Preprocesser with Spriting!"
ProfilePicture = "/images/profile.png"
enableLandingPage = false
AuthorName = "Wellington"
landingPageRedirectUrl = "/install"
GithubURL = "https://github.com/wellington/wellington"

[params.links]
Install = "/docs/install"
